# Generated by Django 6.0.3 on 2026-03-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopDongLaoDong',
            fields=[
                ('ma_hd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_nv', models.CharField(max_length=255)),
                ('loai_hd', models.CharField(max_length=100)),
                ('ngay_bd', models.DateField()),
                ('ngay_kt', models.DateField()),
                ('chuc_vu', models.CharField(max_length=100)),
                ('trang_thai', models.CharField(max_length=50)),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='HopDongLD_CT',
            fields=[
                ('ma_hd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contracts.hopdonglaodong')),
                ('luong_co_ban', models.FloatField()),
                ('luong_theo_gio', models.FloatField()),
                ('so_gio_lam', models.FloatField()),
                ('thuong', models.FloatField()),
                ('phat', models.FloatField()),
            ],
        ),
    ]
