# Generated by Django 6.0.2 on 2026-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_hopdongld_ct_phat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hopdonglaodong',
            name='chuc_vu',
            field=models.CharField(choices=[('QUAN_LY', 'Quản lý'), ('PHUC_VU', 'Phục vụ'), ('PHA_CHE', 'Pha chế'), ('GIU_XE', 'Giữ xe')], max_length=20),
        ),
    ]
