# Generated by Django 6.0.3 on 2026-03-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('ma_tk', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ten_dang_nhap', models.CharField(max_length=100, unique=True)),
                ('mat_khau', models.CharField(max_length=255)),
                ('quyen', models.CharField(max_length=50)),
            ],
        ),
    ]
