# Generated by Django 6.0.3 on 2026-04-15 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='ma_nv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taikhoan', to='employees.nhanvien'),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taikhoan', to=settings.AUTH_USER_MODEL),
        ),
    ]
