# Generated by Django 6.0.3 on 2026-03-31 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('ma_cc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay', models.DateField()),
                ('gio_vao', models.TimeField(blank=True, null=True)),
                ('gio_ra', models.TimeField(blank=True, null=True)),
                ('so_gio_lam', models.FloatField(default=0)),
                ('di_muon', models.BooleanField(default=False)),
                ('ve_som', models.BooleanField(default=False)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien')),
            ],
            options={
                'unique_together': {('ma_nv', 'ngay')},
            },
        ),
    ]
