# Generated by Django 6.0.3 on 2026-04-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamCong',
            fields=[
                ('ma_cc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_lam', models.DateField()),
                ('ca_lam', models.CharField(choices=[('SANG', 'Ca sáng'), ('CHIEU', 'Ca chiều'), ('TOI', 'Ca tối')], max_length=10)),
                ('gio_vao', models.TimeField(blank=True, null=True)),
                ('gio_ra', models.TimeField(blank=True, null=True)),
                ('so_gio_lam', models.FloatField(default=0)),
                ('trang_thai', models.CharField(default='', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
