# Generated by Django 6.0.3 on 2026-04-13 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendances', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamcong',
            name='ma_nv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien'),
        ),
        migrations.AddConstraint(
            model_name='chamcong',
            constraint=models.UniqueConstraint(fields=('ma_nv', 'ngay_lam', 'ca_lam'), name='unique_nv_ngay_ca'),
        ),
    ]
