# Generated by Django 6.0.3 on 2026-04-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamcong',
            name='ma_cc',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
