# Generated by Django 6.0.3 on 2026-03-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('ma_bc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_bd', models.DateField()),
                ('ngay_kt', models.DateField()),
                ('ngay_tao', models.DateField()),
                ('tong', models.FloatField()),
                ('ma_tk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='BaoCao_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nv', models.CharField(max_length=255)),
                ('so_gio_lam', models.FloatField()),
                ('so_ca_lam', models.FloatField()),
                ('thuong', models.FloatField()),
                ('phat', models.FloatField()),
                ('thuc_linh', models.FloatField()),
                ('ma_bc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.baocao')),
                ('ma_luong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.luong')),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien')),
            ],
            options={
                'unique_together': {('ma_nv', 'ma_luong', 'ma_bc')},
            },
        ),
    ]
