# Generated by Django 6.0.3 on 2026-04-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baocao_ct',
            name='chuc_vu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='baocao_ct',
            name='so_ngay_nghi_co_phep',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baocao_ct',
            name='so_ngay_nghi_khong_phep',
            field=models.IntegerField(default=0),
        ),
    ]
