# Generated by Django 6.0.3 on 2026-04-08 07:05

from django.db import migrations, models


def update_trang_thai(apps, schema_editor):
    Luong = apps.get_model('payroll', 'Luong')
    Luong.objects.filter(trang_thai='cho_duyet').update(trang_thai='Dang cho duyet')
    Luong.objects.filter(trang_thai='da_duyet').update(trang_thai='Da duyet')
    Luong.objects.filter(trang_thai='da_tu_choi').update(trang_thai='Da tu choi')


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_trang_thai, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='luong',
            name='trang_thai',
            field=models.CharField(choices=[('Dang cho duyet', 'Đang chờ duyệt'), ('Da duyet', 'Đã duyệt'), ('Da tu choi', 'Đã từ chối')], default='Dang cho duyet', max_length=20),
        ),
    ]
