# Generated by Django 6.0.3 on 2026-04-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_luong_trang_thai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luong',
            name='trang_thai',
            field=models.CharField(choices=[('cho_duyet', 'Đang chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('da_tu_choi', 'Đã từ chối')], default='cho_duyet', max_length=20),
        ),
    ]
