# Generated by Django 6.0.3 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_luong_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='luong',
            name='da_gui',
            field=models.BooleanField(default=False),
        ),
    ]

