# Generated by Django 6.0.3 on 2026-04-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinhanh',
            name='trang_thai',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngưng hoạt động')], default='active', max_length=10),
        ),
    ]
