# Generated by Django 6.0.2 on 2026-03-27 06:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Danh sách nhân viên'},
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='gioi_tinh',
            field=models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, null=True, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='nhanvien',
            name='tk_ngan_hang',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='cccd',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'CCCD phải gồm 12 chữ số')], verbose_name='CCCD'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='chuc_vu',
            field=models.CharField(choices=[('Quản lý', 'Quản lý'), ('Nhân viên', 'Nhân viên')], max_length=50, verbose_name='Chức vụ'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ho_ten',
            field=models.CharField(max_length=100, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ma_chi_nhanh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_viens', to='branches.chinhanh', verbose_name='Chi nhánh'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ma_nv',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Mã nhân viên'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='ngay_sinh',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='sdt',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Số điện thoại chỉ được chứa chữ số')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='vi_tri_vl',
            field=models.CharField(choices=[('Thu ngân', 'Thu ngân'), ('Phục vụ', 'Phục vụ'), ('Quản lý', 'Quản lý'), ('Giữ xe', 'Giữ xe'), ('Pha chế', 'Pha chế')], max_length=50, verbose_name='Vị trí việc làm'),
        ),
    ]
