# Generated by Django 6.0.2 on 2026-04-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_nhanvien_vi_tri_vl'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='employees/avatars/', verbose_name='Ảnh đại diện'),
        ),
    ]
