# Generated by Django 6.0.3 on 2026-03-29 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichLamViec',
            fields=[
                ('ma_llv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ngay_lam', models.DateField()),
                ('ca_lam', models.CharField(max_length=50)),
                ('trang_thai', models.CharField(max_length=50)),
                ('ngay_tao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LichLamViec_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_tri_vl', models.CharField(max_length=100)),
                ('ma_llv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.lichlamviec')),
                ('ma_nv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.nhanvien')),
            ],
            options={
                'unique_together': {('ma_llv', 'ma_nv')},
            },
        ),
    ]
