# Generated by Django 6.0.2 on 2026-04-08 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_chinhanh_trang_thai'),
        ('employees', '0002_remove_nhanvien_vi_tri_vl'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichlamviec',
            name='ma_chi_nhanh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_lam_viec', to='branches.chinhanh'),
        ),
        migrations.AlterField(
            model_name='lichlamviec',
            name='ma_nv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_lam_viec', to='employees.nhanvien'),
        ),
    ]
